apiVersion: v1
kind: Service
metadata:
  name: first-kube-service  # unique key for the service instance
  labels:
    group: example
spec:
  selector:
    # load-balance traffic across Pods matching this label selector
    app: first-kube-deployment
  ports:
    - 
      name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-kube-deploy  # unique key for the deployment instance
  labels:
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-kube-deployment
  template:
    metadata:
      labels:
        app: first-kube-deployment
    spec:
      containers:
        - 
          name: first-kube-pod
          image: karthicksabari/first-kube-cluster:1