apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-volume-persistent-volume
  labels:
    object: persistent-volume
spec:
  capacity:
    storage: 1Gi  # overall available capacity that the volume will have.
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate