apiVersion: v1
kind: Service
metadata:
  name: kube-volume-service  # unique key of the Deployment instance
  labels:
    object: service
spec:
  selector:
    object: kube-volume-pod
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000