apiVersion: v1
kind: Secret
metadata:
  name: kub-tuto-demo-project-mongodb-secret
  labels:
    app: mongodb-secret
    object: secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
