apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-tuto-demo-project-mongo-express-deployment
  labels:
    app: mongo-express-deployment
    object: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      name: kub-tuto-demo-project-mongo-express-pod
      labels:
        app: mongo-express
        object: pod
    spec:
      containers:
        - 
          name: kub-tuto-demo-project-mongo-express-container
          image: mongo-express
          ports:
            - 
              name: http
              protocol: TCP
              containerPort: 8081
          env:
            -
              name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: kub-tuto-demo-project-mongodb-secret
                  key: mongo-root-username
            -
              name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: kub-tuto-demo-project-mongodb-secret
                  key: mongo-root-password
            - 
              name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: kub-tuto-demo-project-mongo-express-configmap
                  key: database-url
