apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-tuto-demo-project-mongodb-deployment
  labels:
    app: mongodb-deployment
    object: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: kub-tuto-demo-project-mongodb-pod
      labels:
        app: mongo
        object: pod
    spec:
      containers:
        - 
          name: kub-tuto-demo-project-mongodb-container
          image: mongo
          ports:
            - 
              name: http
              protocol: TCP
              containerPort: 27017
          env:
            - 
              name: MONGO_INITDB_ROOT_USERNAME
              valueFrom: 
                secretKeyRef: 
                  name: kub-tuto-demo-project-mongodb-secret
                  key: mongo-root-username
            - 
              name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: kub-tuto-demo-project-mongodb-secret
                  key: mongo-root-password
