kind: Service
apiVersion: v1
metadata:
  name: kub-tuto-demo-project-mongo-express-service
  labels:
    app: mongo-express-service
    object: service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    -
      name: http
      protocol: TCP
      targetPort: 8081  # container port
      port: 80          # service port
      nodePort: 30000   # node / loadbalancer port
