apiVersion: v1
kind: Service
metadata:
  name: kube-network-service-auth
  labels:
    object: service
spec:
  selector:
    app: auth
  type: ClusterIP  # this will not be reachable from outside
  ports:
    - 
      name: http
      protocol: TCP
      port: 80
      targetPort: 80  # port exposed by the container