apiVersion: v1
kind: Service
metadata:
  name: kube-network-service-frontend
  labels:
    object: service
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - 
      name: http
      protocol: TCP
      port: 80
      targetPort: 80  # port exposed by the container