apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-network-frontend-deployment
  labels:
    object: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: kube-network-frontend-pod
      labels:
        object: pod
        app: frontend
    spec:
      containers:
        - 
          name: kube-network-frontend-container
          image: karthicksabari/kube-network-frontend:2
