apiVersion: v1
kind: Service
metadata:
  name: kube-network-service-tasks
  labels:
    object: service
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - 
      name: http
      protocol: TCP
      port: 8000
      targetPort: 8000  # port exposed by the container