version: '3.9'

services:
  mongodb:
    container_name: goals_mongodb
    image: 'mongo'
    volumes:
      - data:/data/db
    env_file: 
      - ./env/mongo.env

  backend:
    container_name: goals_node_app
    build: ./backend  # shorter-form
    ports:
      - '80:80'
    volumes: 
      - logs:/app/logs
      - ./backend:/app  # relative-path unlike command line
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb  # this creates mongodb before backend

  frontend:
    container_name: goals_react_app
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
